### ISSUE TITLE
Does it work for Wordpress?

### ISSUE THREAD

**Issue by AlexWT** [marcofiset/Testify.php#13]
How can i setup it so that i can test wordpress plugins? When i require the file i want, it gie me php error "function **\* not defined".

**Comment by marcofiset** [comment]
Sorry for the late response, I just noticed that I was not 'Watching' my own project, how could that be!? 

What you could do is implement your plugin in a separate library and make it completely independant from Wordpress and test that. Then you can have your real plugin that uses your library and interfaces it with Wordpress. I am sorry if that does not make sense, I never created a Wordpress plugin before. But that could be an idea.

**Comment by AlexWT** [comment]
Sorry for my late response too. Well, i kinda understand the idea, but it doesn't seem like a good solution. Its like doing one thing twice + its hard to maintain if i understand currectly. I believe that testify can become very famous if it is implemented to test wordpress plugins and themes.

**Comment by marcofiset** [comment]
Actually, this won't make you do the work twice. Have you ever heard of the Adapter pattern? It is considered very good practice to encapsulate a library with a well designed API and test _that_, then create an adapter so you can plug it into what you want, like a Wordpress plugin.

I'm sorry to say that I don't have any interest in Wordpress, so this will not be implemented, at least not by me. I want Testify to remain what it is : a simple, general purpose testing utility. Feel free to fork the project if you are willing to implement Wordpress testing, but it is not something I will spend time on.
