### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by sgchris** [marcofiset/Testify.php#17]
When no tests / assertions are defined the result is 0 passes divided by 0 total.

**Comment by marcofiset** [comment]
I don't want to sound arrogant, but why are you running your tests if you don't have any?

**Comment by sgchris** [comment]
I have checked out a new non familiar code from non familiar source, so I defined a test skeleton and wanted to run the script before defining some `assert`s. Just to check that the script works, and I can go on and create tests.

I guess you can agree with me that getting PHP error, no matter what the input was, is not a good position.

Anyway, I liked your code and I extended it for testing RESTFul APIs as well. You are welcome to review the code and give some feedbacks.
Thanks.

**Comment by BafS** [comment]
I have created a pull request to fix this issue. See my fork.
