### ISSUE TITLE
What license is this project published under?

### ISSUE THREAD

**Issue by aichingm** [marcofiset/Testify.php#19]
As the title says I would like to know under which software license this code is published?

Mario

Edit I just found it in the composer file (GPL) any hint about the version 2/3?

**Comment by BafS** [comment]
Hi,

The first creator ([martinaglv](https://github.com/marco-fiset/Testify.php/graphs/contributors)) did not include any type of license.
I have ported the code to PSR and put the GPL license without much tough.
