### ISSUE TITLE
ArrayAccess for tests

### ISSUE THREAD

**Issue by netzhuffle** [marcofiset/Testify.php#3]
Another idea, how we could use ArrayAccess:

Today:
$tf->test(function($tf) {
    /* … */
});
$tf->test("Testing the add() method", function($tf) {
    /* … */
});

Idea:
$tf[] = function($tf) {
    /* … */
};
$tf["Testing the add() method"] = function($tf) {
    /* … */
};

Not that beautiful, but easy to understand.
What do you think?

**Comment by marcofiset** [comment]
As you said, not that beautiful. This won't be implemented.
